#!/usr/bin/env bash
# Fix my server with these lines
sudo apt-get update -y 
sudo apt-get install -y apache2
sudo service apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo service apache2 restart
